#' Line Plot for Comparing Pseudo and Observed WTC
#'
#' Generates a line plot comparing pseudo and observed WTC, using data created
#' using [compareIPS()].
#'
#' @param df.rsq Dataframe. Generally generated by the [compareIPS()] function.
#' @param col.plot Vector of characters. Two characters containing Hex colour codes. Default is blue and green.
#' @param ncol Numeric. Number of columns to use for facets if multiple Features. Default is `1`.
#'
#' @return A `ggplot` object.
#' 
#' @seealso \code{\link{compareIPS}}
#' 
#' @author Irene Sophia Plank (\email{10planki@@gmail.com})
#' @import ggplot2
#' @import dplyr
#' @export

plotWTCcomp = function(df.rsq, col.plot = c("#08519c", "#4B9C79"), ncol = 1) {
  
  minFreq = floor(min(df.rsq$Frequency) * 5) / 5
  maxFreq = ceiling(max(df.rsq$Frequency) * 5) / 5
  
  # recode the pseudoDyad variable 
  df.rsq = df.rsq |>
    mutate(
      Method = if_else(Method == "observed", "observed", "pseudo"),
      Evaluation = if_else(is.na(Evaluation), "comparable", "different")
    )
  
  # plot
  p = df.rsq |>
    ggplot(aes(x = log(Frequency), y = AVG, fill = Method, colour = Method)) + 
    geom_line() + 
    geom_ribbon(aes(ymin = pmax(0, AVG - STD), 
                    ymax = pmin(1, AVG + STD)),
                alpha = 0.2, colour = NA) +
    geom_point(data = df.rsq |> filter(Evaluation == "different") |>
                 group_by(Method, Frequency, across(any_of('Feature')), Direction) |>
                 summarise(AVG = mean(AVG),
                           .groups = "drop"),
               aes(shape = Direction), show.legend = F) + 
    theme_bw() +
    scale_fill_manual(values = col.plot) + 
    scale_colour_manual(values = col.plot) + 
    scale_y_continuous(name = "Coherence") + 
    scale_x_continuous(
      name = "Frequency",
      breaks = log(seq(from = minFreq, to = maxFreq, length.out = 5)),
      labels = seq(from = minFreq, to = maxFreq, length.out = 5)
    ) + theme(legend.position = "bottom", legend.title = element_blank())
  
  if (length(unique(df.rsq$Feature)) > 1) p = p + facet_wrap(. ~ Feature, ncol = ncol)
  
  return(p)
  
}

#' Rose Plot of Wavelet Coherence Phase
#'
#' Generates a rose plot of one dyad's wavelet coherence phase. 
#'
#' @param df Dataframe. Generally generated by the [convertWTC()] function.
#' @param Bins Numeric. Number of Bins in which phases should be separated. 
#' @param col.plot Character vector containing Hex colour code. Default is green.
#'
#' @return A `ggplot` object.
#' 
#' @seealso \code{\link{convertWTC}} \code{\link{extractWTC}}
#' 
#' @author Irene Sophia Plank (\email{10planki@@gmail.com})
#' @import ggplot2
#' @import dplyr
#' @export

plotPhaseRose = function(df, Bins, col.plot = "#4B9C79"){
  
  # check that the dataframe only contains one dyad
  if (length(unique(df$Dyad)) > 1) stop("This function plots data from one Dyad.")
  
  # label with Identifiers or with left and right in the case of pseudoDyad
  if (df$pseudoDyad[1]) {
    ll = "Left Leading"
    rl = "Right Leading"
  } else {
    ll = sprintf("%s Leading", gsub("-.*", "", df$Dyad[1]))
    rl = sprintf("%s Leading", gsub(".*-", "", df$Dyad[1]))
  }
  
  p = df |> 
    filter(WithinCOI) |> 
    mutate(
      phaseBin = cut(Phase, breaks = seq(-pi, pi, length.out = Bins), include.lowest = TRUE)
    ) |> 
    count(phaseBin, .drop = F) |> 
    mutate(
      Angle = seq(-pi + (pi/Bins), pi - (pi/Bins), length.out = Bins-1)
    ) |> 
    ggplot(aes(x = Angle, y = n)) +
    geom_col(fill = col.plot, color = "white") +
    coord_polar(start = pi, clip = "off") +
    scale_x_continuous(
      limits = c(-pi, pi), 
      breaks = c(-pi, -pi/2, 0, pi/2),
      labels = c("Anti-phase", ll, "In-phase", rl)
    ) +
    labs(
      title = "Phase Difference Distribution",
      subtitle = expression("Thresholded to be significant and inside valid COI"),
      x = NULL,
      y = NULL
    ) + theme_bw() +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(), 
      panel.border = element_blank()
    )
  
  return(p)
  
}
