#' Line Plot for Comparing Pseudo and Observed WTC
#'
#' Generates a line plot comparing pseudo and observed WTC, aggregated by [aggWTC()]
#' and then compared using [compareWTC()].
#'
#' @param df.rsq Dataframe. Generally generated by the [compareWTC()] function.
#' @param col.plot Vector of characters. Two characters containing Hex colour codes. 
#'
#' @return A `ggplot` object.
#' 
#' @seealso \code{\link{aggWTC}} \code{\link{compareWTC}}
#' 
#' @author Irene Sophia Plank (\email{10planki@@gmail.com})
#' @import ggplot2
#' @import dplyr
#' @export

plotWTCcomp = function(df.rsq, col.plot = c("#08519c", "#4B9C79")) {
  
  minFreq = min(df.rsq$Frequency)
  maxFreq = max(df.rsq$Frequency)

  # plot
  p = df.rsq |>
    group_by(pseudoDyad, Frequency, Bin) |>
    summarise(
      Rsq_std = sd(Rsq_avg),
      Rsq_avg = mean(Rsq_avg),
      .groups = "drop"
    ) |>
    ggplot(aes(x = log(Frequency), y = Rsq_avg, fill = pseudoDyad, colour = pseudoDyad)) + 
    geom_line() + 
    geom_ribbon(aes(ymin = pmax(0, Rsq_avg - Rsq_std), 
                    ymax = pmin(1, Rsq_avg + Rsq_std)),
                alpha = 0.2, colour = NA) +
    geom_point(data = df.rsq |> filter(p.adj < 0.05) |>
                 group_by(pseudoDyad, Frequency, Bin) |>
                 summarise(Rsq_avg = mean(Rsq_avg),
                           .groups = "drop")) + 
    theme_bw() +
    scale_fill_manual(values = col.plot) + 
    scale_colour_manual(values = col.plot) + 
    scale_x_continuous(
      name = "Frequency",
      breaks = seq(from = log(minFreq), to = log(maxFreq), length.out = 5),
      labels = exp(seq(from = log(minFreq), to = log(maxFreq), length.out = 5))
    ) + theme(legend.position = "bottom")
  
  if (length(unique(df.rsq$Feature)) > 1) p = p + facet_wrap(. ~ Feature)
  
  return(p)

}

#' Rose Plot of Wavelet Coherence Phase
#'
#' Generates a rose plot of one dyad's wavelet coherence phase. 
#'
#' @param df.dyad Dataframe. Generally generated by the [convertWTC()] function.
#' @param Bins Numeric. Number of Bins in which phases should be separated. 
#' @param col.plot Character vector containing Hex colour code. 
#'
#' @return A `ggplot` object.
#' 
#' @seealso \code{\link{convertWTC}} \code{\link{extractWTC}}
#' 
#' @author Irene Sophia Plank (\email{10planki@@gmail.com})
#' @import ggplot2
#' @import dplyr
#' @export

plotPhaseRose = function(df.dyad, Bins, col.plot = "#4B9C79"){
  
  # check that the dataframe only contains one dyad
  if (length(unique(df.dyad$Dyad)) > 1) stop("This function plots data from one Dyad.")
  
  # label with Identifiers or with left and right in the case of pseudoDyad
  if (df.dyad$pseudoDyad[1]) {
    ll = "Left Leading"
    rl = "Right Leading"
  } else {
    ll = sprintf("%s Leading", gsub("-.*", "", df.dyad$Dyad[1]))
    rl = sprintf("%s Leading", gsub(".*-", "", df.dyad$Dyad[1]))
  }
  
  p = df.dyad |> 
    filter(WithinCOI) |> 
    mutate(
      phaseBin = cut(Phase, breaks = seq(-pi, pi, length.out = Bins), include.lowest = TRUE)
    ) |> 
    count(phaseBin, .drop = F) |> 
    mutate(
      Angle = seq(-pi + (pi/Bins), pi - (pi/Bins), length.out = Bins-1)
    ) |> 
    ggplot(aes(x = Angle, y = n)) +
    geom_col(fill = col.plot, color = "white") +
    coord_polar(start = pi, clip = "off") +
    scale_x_continuous(
      limits = c(-pi, pi), 
      breaks = c(-pi, -pi/2, 0, pi/2),
      labels = c("Anti-phase", ll, "In-phase", rl)
    ) +
    labs(
      title = "Phase Difference Distribution",
      subtitle = expression("Thresholded to be significant and inside valid COI"),
      x = NULL,
      y = NULL
    ) + theme_bw() +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(), 
      panel.border = element_blank()
    )
  
  return(p)
  
}

#' Plot Aggregated Wavelet Coherence by Frequency
#'
#' Generates a line plot of one dyad's wavelet coherence by frequency. 
#'
#' @param df.dyad Dataframe. Generally generated by the [convertWTC()] function.
#' @param col.plot Character. Containing the Hex colour code for the plot.  
#'
#' @return A `ggplot` object.
#' 
#' @seealso \code{\link{convertWTC}} \code{\link{extractWTC}}
#' 
#' @author Irene Sophia Plank (\email{10planki@@gmail.com})
#' @import ggplot2
#' @import dplyr
#' @export

plotWTCLine = function(df.dyad, col.plot = "#08519c"){
  
  # check that the dataframe only contains one dyad
  if (length(unique(df.dyad$Dyad)) > 1) stop("This function plots data from one Dyad.")
  
  p = df.dyad |> 
    filter(WithinCOI) |> 
    group_by(Period, Frequency) |> 
    summarise(
      Rsq_mean   = mean(Rsq),
      Rsq_SD     = sd(Rsq),
      .groups = "drop"
    ) |> drop_na() |>
    ggplot(aes(x = Frequency, y = Rsq_mean)) +
    # shaded area for +- SD
    geom_ribbon(
      aes(ymin = pmax(0, Rsq_mean - Rsq_SD), ymax = pmin(1, Rsq_mean + Rsq_SD)),
      alpha = 0.2, colour = col.plot
    ) +
    # mean Coherence Line
    geom_line(linewidth = 1, colour = col.plot) +
    geom_point(size = 1.5, colour = col.plot) +
    scale_y_continuous(limits = c(0, 1)) +
    labs(
      title = "Mean Wavelet Coherence Across Frequencies",
      subtitle = "Shaded area represents ±1 SD (COI-masked)",
      x = "Frequency (Hz)",
      y = expression("Mean Coherence (" * R^2 * ")")
    ) + theme_bw() + theme(legend.position = "bottom")
  
  return(p)
  
}
