#' Plot Comparison of Observed and Pseudo Windowed-Lagged Cross-Correlations
#'
#' Generates line plots comparing observed WLCC against various pseudo-WLCC control 
#' distributions across different time lags, automatically highlighting statistically 
#' credible lags. The resulting visualisation uses facet wrapping to organize 
#' different tracking features and, if available, by summary statistics (peak and mean).
#'
#' @param df Dataframe. The `*_pseudo-comp.csv` dataset generated by the [featWLCC()] pipeline.
#' @param ncol Numeric. Number of columns to use in the `ggplot2::facet_wrap()` layout. Default is `3`.
#' @param cols.wlcc Named character vector. Color codes mapping the empirical WLCC 
#'   and distinct types of pseudo-WLCC lines. Default features explicit hex assignments for 
#'   `"WLCC"`, `"pseudoSegment-WLCC"`, `"pseudoDyad-WLCC"`, and `"pseudoData-WLCC"`.
#' @param cols.cred Named character vector. Color codes highlighting lag intervals based on 
#'   statistical credibility status. Expected names are `"credible"` and `"not credible"`.
#'
#' @return A `ggplot` object representing the comparison line plots.
#' 
#' @author Irene Sophia Plank (\email{10planki@@gmail.com})
#' @import ggplot2
#' @import dplyr
#' @export

plotWLCCcomp = function(df, ncol = 3,
                        cols.wlcc = c("WLCC" = "#1B9E77", "pseudoSegment-WLCC" = "#FFB6C1", 
                                      "pseudoDyad-WLCC" = "#CAE1FF", "pseudoData-WLCC" = "#C9A0DC"), 
                        cols.cred = c("credible" = "#FFFC80", "not credible" = "white")) {
  
  # get the peak lags
  df.lag = df |>
    group_by(Stat, Feature) |>
    filter(observed == max(observed)) |>
    mutate(
      label = sprintf("Peak: %.2fs", lag),
      ypos  = pseudo - pseudo.sd/2
    )
  
  if (length(unique(df$Stat)) > 1) {
    
    return(df |>
             tidyr::pivot_longer(cols = starts_with(c("observed", "pseudo"))) |>
             mutate(temp = if_else(grepl(".*sd", name), "SD", "mean"),
                    Type = case_when(grepl("observ.*", name) ~ "WLCC", 
                                     Method == "Dyad" ~ "pseudoDyad-WLCC", 
                                     Method == "Seg"  ~ "pseudoSegment-WLCC",
                                     Method == "Data" ~ "pseudoData-WLCC")) |>
             select(-name) |>
             tidyr::pivot_wider(names_from = temp) |>
             group_by(Type, Feature) |>
             mutate(yTile = mean(mean, na.rm = T)) |>
             group_by(Feature, Stat, lag) |> 
             mutate(credible = case_when(sum(credible == "credible lags") > 0 ~ "credible",
                                         T ~ "not credible")) |>
             ungroup() |> 
             ggplot() +  
             geom_tile(aes(fill = credible, x = lag, y = yTile, height = Inf), alpha = 0.66) +
             geom_ribbon(aes(x = lag, y = mean, group = Type, fill = Type, 
                             ymin = mean - SD, ymax = mean + SD), 
                         alpha = 0.5) +
             geom_line(aes(x = lag, y = mean, group = Type, colour = Type), linewidth = 1) +
             geom_vline(data = df.lag, aes(xintercept = lag), colour = "black") + 
             geom_label(data = df.lag, aes(x = lag, y = ypos, label = label),  size = 2.5) + 
             facet_wrap(Stat ~ Feature, scale = "free_y", ncol = ncol) +  
             scale_fill_manual(values = c(cols.cred, 
                                          cols.wlcc), 
                               breaks = c("WLCC", "pseudoDyad-WLCC", "pseudoSegment-WLCC", "pseudoData-WLCC", 
                                          "credible")) + 
             scale_colour_manual(values = cols.wlcc, 
                                 guide = "none") +
             theme_bw() + 
             theme(legend.position = "bottom", legend.title = element_blank(),
                   axis.title.y = element_blank())
    )
  } else {
    
    return(df |>
             tidyr::pivot_longer(cols = starts_with(c("observed", "pseudo"))) |>
             mutate(temp = if_else(grepl(".*sd", name), "SD", "mean"),
                    Type = case_when(grepl("observ.*", name) ~ "WLCC", 
                                     Method == "Dyad" ~ "pseudoDyad-WLCC", 
                                     Method == "Seg"  ~ "pseudoSegment-WLCC",
                                     Method == "Data" ~ "pseudoData-WLCC")) |>
             select(-name) |>
             tidyr::pivot_wider(names_from = temp) |>
             group_by(Type, Feature) |>
             mutate(yTile = mean(mean, na.rm = T)) |>
             group_by(Feature, Stat, lag) |> 
             mutate(credible = case_when(sum(credible == "credible lags") > 0 ~ "credible",
                                         T ~ "not credible")) |>
             ungroup() |> 
             ggplot() +  
             geom_tile(aes(fill = credible, x = lag, y = yTile, height = Inf), alpha = 0.66) +
             geom_ribbon(aes(x = lag, y = mean, group = Type, fill = Type, 
                             ymin = mean - SD, ymax = mean + SD), 
                         alpha = 0.5) +
             geom_line(aes(x = lag, y = mean, group = Type, colour = Type), linewidth = 1) +
             geom_vline(data = df.lag, aes(xintercept = lag), colour = "black") + 
             geom_label(data = df.lag, aes(x = lag, y = ypos, label = label),  size = 2.5) + 
             facet_wrap(. ~ Feature, scale = "free_y", ncol = ncol) +  
             scale_fill_manual(values = c(cols.cred, 
                                          cols.wlcc), 
                               breaks = c("WLCC", "pseudoDyad-WLCC", "pseudoSegment-WLCC", "pseudoData-WLCC", 
                                          "credible")) + 
             scale_colour_manual(values = cols.wlcc, 
                                 guide = "none") +
             theme_bw() + 
             theme(legend.position = "bottom", legend.title = element_blank(),
                   axis.title.y = element_blank())
    )
  }
  
}