#' Plot Comparison of Observed and Pseudo Windowed-Lagged Cross-Correlations
#'
#' Generates line plots comparing observed WLCC against various pseudo-WLCC control 
#' distributions across different time lags, automatically highlighting statistically 
#' credible lags by using darker colours. The resulting visualisation uses facet 
#' wrapping to organise different tracking features.
#'
#' @param df Dataframe. The `*_pseudo-comp.csv` dataset generated by [compareIPS()].
#' @param ncol Numeric. Number of columns to use in the `ggplot2::facet_wrap()` layout. Default is `2`.
#' @param term Character. Which term is used for describing a relevant difference.
#'   Default is `significant`.
#' @param col.plot Vector of characters. Three characters containing Hex colour codes:
#'   one for observed values, one for pseudo and one for the highlights. 
#'   Default is `blue`, `green` and `lightblue`.
#'
#' @return A `ggplot` object representing the comparison line plots.
#' 
#' @author Irene Sophia Plank (\email{10planki@@gmail.com})
#' @import ggplot2
#' @import dplyr
#' @export

plotWLCCcomp = function(df, ncol = 2, term = "significant",
                        col.plot = c("#08519c", "#4B9C79", "lightblue")) {
  
  checkDF(df, c("Method", "Feature", "Lag", "Evaluation", "AVG", "STD"))
  
  # convert method to be uniform
  df = df |>
    mutate(
      Method = if_else(Method == "observed", "observed", "pseudo"),
      # replace all SDs that are NA with 0
      STD = if_else(is.na(STD), 0, STD)
    )
  
  # add the names to the colour vector
  names(col.plot) = c("observed", "pseudo", term)
  
  # get the peak lags
  df.lag = df |>
    group_by(Feature, Method) |>
    filter(AVG == max(AVG) & Method == "observed") |>
    mutate(
      label = sprintf("Peak: %.2fs", Lag),
      ypos  = if_else(STD > 0, AVG + STD*2/3, -0.02)
    )
  
  # get where to use shaded region for the lags that are different
  df.back = df |> 
    filter(Method == "observed") |>
    arrange(Feature, Lag) |>
    mutate(
      rel = !is.na(Evaluation) & Evaluation == "*",
      bid = cumsum(!rel & lag(rel, default = TRUE))
    ) |>
    group_by(Feature, bid) |>
    summarise(
      xmin = first(Lag[rel]),
      xmax = last(Lag[rel]),
      .groups = "drop"
    ) |>
    select(-bid) |> tidyr::drop_na()
    
  p = df |>
     ggplot() +
     geom_rect(data = df.back, 
               aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf,
                   fill = "observed exceeding pseudo"),
               alpha = 0.3) +
     geom_ribbon(aes(x = Lag, y = AVG, group = Method, fill = Method, 
                     ymin = AVG - STD, ymax = AVG + STD), 
                 alpha = 0.4) +
     geom_line(aes(x = Lag, y = AVG, group = Method, colour = Method), linewidth = 1, alpha = 0.8) +
     geom_vline(data = df.lag, aes(xintercept = Lag), colour = "black") + 
     geom_label(data = df.lag, aes(x = Lag, y = ypos, label = label),  size = 2.5) + 
     facet_wrap(. ~ Feature, scale = "free_y", ncol = ncol) +  
     scale_fill_manual(values = col.plot,
                       breaks = c("observed exceeding pseudo")) +
     scale_colour_manual(values = col.plot) +
     theme_bw() + 
     theme(legend.position = "bottom", legend.title = element_blank(),
           axis.title.y = element_blank())
  
  return(p)
  
}
