#' Plot Comparison of Observed and Pseudo Windowed-Lagged Cross-Correlations
#'
#' Generates line plots comparing observed WLCC against various pseudo-WLCC control 
#' distributions across different time lags, automatically highlighting statistically 
#' credible lags by using darker colours. The resulting visualisation uses facet 
#' wrapping to organise different tracking features.
#'
#' @param df Dataframe. The `*_pseudo-comp.csv` dataset generated by [compareIPS()].
#' @param ncol Numeric. Number of columns to use in the `ggplot2::facet_wrap()` layout. Default is `2`.
#' @param col.plot Vector of characters. Two characters containing Hex colour codes. Default is blue and green.
#'
#' @return A `ggplot` object representing the comparison line plots.
#' 
#' @author Irene Sophia Plank (\email{10planki@@gmail.com})
#' @import ggplot2
#' @import dplyr
#' @export

plotWLCCcomp = function(df, ncol = 2, 
                        col.plot = c(observed = "#08519c", pseudo = "#4B9C79")) {
  
  checkDF(df, c("Method", "Feature", "Lag", "Evaluation", "AVG", "STD"))
  
  # convert method to be uniform
  df = df |>
    mutate(
      Method = if_else(Method == "observed", "observed", "pseudo")
    )
  
  # get the peak lags
  df.lag = df |>
    group_by(Feature, Method) |>
    filter(AVG == max(AVG) & Method == "observed") |>
    mutate(
      label = sprintf("Peak: %.2fs", Lag),
      ypos  = AVG + STD
    )
    
  df |>
     ggplot() +  
     geom_ribbon(aes(x = Lag, y = AVG, group = Method, fill = Method, 
                     ymin = AVG - STD, ymax = AVG + STD), 
                 alpha = 0.2) +
     geom_ribbon(data = df |> filter(Evaluation == "*"),
                 aes(x = Lag, y = AVG, group = Method, fill = Method, 
                     ymin = AVG - STD, ymax = AVG + STD), 
                 alpha = 0.4) +
     geom_line(aes(x = Lag, y = AVG, group = Method, colour = Method), linewidth = 1, alpha = 0.4) +
     geom_line(data = df |> filter(Evaluation == "*"),
               aes(x = Lag, y = AVG, group = Method, colour = Method), linewidth = 1, alpha = 0.8) +
     geom_vline(data = df.lag, aes(xintercept = Lag), colour = "black") + 
     geom_label(data = df.lag, aes(x = Lag, y = ypos, label = label),  size = 2.5) + 
     facet_wrap(. ~ Feature, scale = "free_y", ncol = ncol) +  
     scale_fill_manual(values = col.plot) +
     scale_colour_manual(values = col.plot) +
     theme_bw() + 
     theme(legend.position = "bottom", legend.title = element_blank(),
           axis.title.y = element_blank())
  
  return(p)
  
}
